@HotelListing.Api_HostAddress = https://localhost:7041



GET {{HotelListing.Api_HostAddress}}/api/countries

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "Test country 3",
  "shortName": "TC3"
}

###

DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{countryid}}

###

@countryid = 3
GET {{HotelListing.Api_HostAddress}}/api/countries/{{countryid}}

###


GET {{HotelListing.Api_HostAddress}}/api/countries/3

###

PUT {{HotelListing.Api_HostAddress}}/api/countries/{{countryid}}
Content-Type: application/json

{
  "countryId": 2,
  "name": "Countryia",
  "shortName": "CRI"
}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name": "Test Hotel 55",
  "Address": "Test Address 5",
  "Rating": 4.5,
  "CountryId": 2
}

###


DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###
@id=3
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

@id=1
PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id": 1,
  "Name": "Test Hotel 35",
  "Address": "Test Address 335",
  "Rating": 4.25,
  "CountryId": 3
}

###
