@HotelListing.Api_HostAddress = https://localhost:7041


GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  
  "id": 3,
  "name": "Graddnd Plaza",
  "address": "12453 Main St",
  "rating": 2.834
  
}

###

@id=1
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

@id=1
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

@id=3
PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "name": "Graddnd Plaza",
  "address": "12453 Main Street St",
  "rating": 2.834
}

###
